version: "3.4"
services:
  db:
    image: mdillon/postgis:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - db_user=${POSTGRES_USER}
      - db_password=${POSTGRES_PASSWORD}
      - db_name=${POSTGRES_DB}
      - db_host=db
      - db_port=${POSTGRES_PORT}
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG

  #  nginx:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile.nginx
  #    volumes:
  #      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #      - ./certs:/etc/nginx/external:ro
  #      - ./certificate_authority:/usr/local/share/ca-certificates:ro
  #    ports:
  #      - "443:443"
  #    environment:
  #      - DH_SIZE=2048
  #    depends_on:
  #      - web
  
  react:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/todo
      - nodemodulesdata:/todo/node_modules
    depends_on:
      - web
    environment:
      - CHOKIDAR_USEPOLLING=$CHOKIDAR_USEPOLLING
      # this next line is needed to allow e2e to work
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    stdin_open: true
  e2e:
    image: cypress/included:5.1.0
    volumes:
      - ./frontend:/e2e
    working_dir: /e2e
    environment:
      - CYPRESS_baseUrl=http://react:3000
    depends_on:
      - db
      - web
      - react
  # this e2e open does not work yet
  # e2e_open:
  #   image: cypress/included:5.1.0
  #   volumes:
  #     - ./frontend:/e2e
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #   environment:
  #     - DISPLAY=$IP:0
  #   working_dir: /e2e
  #   entrypoint:
  #     - cypress
  #   command:
  #     - open
  # depends_on:
  #   - db
  #   - web
  #   - react  
volumes:
  pgdata:
  nodemodulesdata: