# Generated by Django 2.2.14 on 2020-07-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20200717_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='todo',
        ),
    ]
